### ISSUE TITLE
dependency on a non-existent service "security.csrf.token_manager"

### ISSUE THREAD

**Issue by pradipchitrakar** [fantoine/csrf-route-bundle#1]
After installing this bundle, I get this error:
The service "fantoine_csrf_route.manager" has a dependency on a non-existent service "security.csrf.token_manager"

I am using symfony 2.3

Also in the documentation there is a typo for new Fantoine\CsrfRouteBundle\FantoineCsrfRouteBundleBundle()

there is double BundleBundle

**Comment by fantoine** [comment]
Hi

The "security.csrf.token_manager" has been added in Symfony 2.4 to split the now-deprecated "security.context" service. However I can try to handle retrocompatibility with Symfony 2.3.

And I'll fix the typo too.

**Comment by fantoine** [comment]
The problems was not with the security.context service but the symfony/security-csrf sub-module which has been added on Symfony 2.4.

It should be compatible with Symfony 2.3 now.
Please try again and tell me if it works.

**Comment by pradipchitrakar** [comment]
Thanks
