### ISSUE TITLE
Major speed problem

### ISSUE THREAD

**Issue by enumag** [fantoine/csrf-route-bundle#2]
This bundle causes major speed drop due to the fact that it relies on `RouterInterface::getRouteCollection()`. This method should NOT be used in runtime - see https://github.com/symfony/symfony/issues/7368#issuecomment-15146130.

I would have reported it to https://github.com/Genedys/csrf-route-bundle but it does not have issues enabled.

I might be able to fix this myself but I want to know if you guys are still active and if I should send a PR or rather fork it.

ping @fantoine @Maxwell21 @wolfx

**Comment by fantoine** [comment]
Hi @enumag. Thanks for reporting this.
I opened issues on https://github.com/Genedys/csrf-route-bundle so you can post your issue their.
Also, feel free to push a PR to solve this issue and I'll merge it.

**Comment by enumag** [comment]
@fantoine Did you see the pull request? Can I get your feedback?

**Comment by fantoine** [comment]
Merged in [Genedys/csrf-route-bundle](https://github.com/Genedys/csrf-route-bundle)

**Comment by enumag** [comment]
@fantoine Are you getting notifications from Genedys/csrf-route-bundle? I'm still waiting for https://github.com/Genedys/csrf-route-bundle/pull/3 to be merged.
